{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.lg-buddy;
  bscpylgtv = pkgs.python3Packages.callPackage ./bscpylgtv.nix { };
  defaultPackage = pkgs.callPackage ./package.nix {
    inherit bscpylgtv;
    source = ../.;
  };

  boolSetting = enabled: if enabled then "enabled" else "disabled";
  pairingFile = "${cfg.pairingStateDirectory}/client-key.sqlite";
  userGroup = lib.defaultTo "users" (lib.attrByPath [ cfg.user "group" ] null config.users.users);
  generatedConfig = pkgs.writeText "lg-buddy-config.env" ''
    # Generated by the LG Buddy declarative Nix integration.
    tvs_primary_ip=${cfg.tv.ip}
    tvs_primary_mac=${cfg.tv.mac}
    tvs_primary_input=${cfg.tv.input}
    screen_idle_blank=${boolSetting cfg.screen.idleBlank}
    screen_backend=${cfg.screen.backend}
    screen_idle_timeout=${toString cfg.screen.idleTimeout}
    screen_restore_policy=${cfg.screen.restorePolicy}
    system_sleep_wake_policy=${boolSetting cfg.systemSleepWake}
    updates_auto_check=${boolSetting cfg.updates.autoCheck}
    updates_channel=${cfg.updates.channel}
  '';

  commonEnvironment = {
    LG_BUDDY_BSCPYLGTV_KEY_FILE = pairingFile;
    LG_BUDDY_BSCPYLGTV_OWNER_USER = cfg.user;
    LG_BUDDY_CONFIG = generatedConfig;
    LG_BUDDY_SKIP_SYSTEMD_ACTIONS = "1";
  };

  dispatcherEnvironment = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: value: "export ${name}=${lib.escapeShellArg value}") commonEnvironment
  );

  rootServiceHardening = {
    CapabilityBoundingSet = [
      "CAP_SETGID"
      "CAP_SETUID"
    ];
    LockPersonality = true;
    PrivateDevices = true;
    PrivateTmp = true;
    ProtectControlGroups = true;
    ProtectHome = true;
    ProtectKernelModules = true;
    ProtectKernelTunables = true;
    ProtectSystem = "strict";
    ReadWritePaths = [
      "/run/lg_buddy"
      cfg.pairingStateDirectory
    ];
    RestrictAddressFamilies = [
      "AF_INET"
      "AF_INET6"
      "AF_UNIX"
    ];
    RestrictRealtime = true;
  };
in
{
  options.services.lg-buddy = {
    enable = lib.mkEnableOption "the experimental LG Buddy declarative Nix integration";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage;
      defaultText = lib.literalExpression "pkgs.callPackage ./nix/package.nix { }";
      description = "LG Buddy package used by the declared services.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      description = ''
        Desktop user that owns the persistent TV pairing state and runs the
        session service.
      '';
    };

    tv = {
      ip = lib.mkOption {
        type = lib.types.strMatching "[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+";
        description = "IPv4 address of the primary TV.";
      };

      mac = lib.mkOption {
        type = lib.types.strMatching "([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}";
        description = "MAC address of the primary TV, used for Wake-on-LAN.";
      };

      input = lib.mkOption {
        type = lib.types.enum [
          "HDMI_1"
          "HDMI_2"
          "HDMI_3"
          "HDMI_4"
        ];
        default = "HDMI_1";
        description = "TV input connected to this machine.";
      };
    };

    screen = {
      idleBlank = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether the session service blanks and restores the TV on idle.";
      };

      backend = lib.mkOption {
        type = lib.types.enum [
          "auto"
          "gnome"
          "swayidle"
        ];
        default = "auto";
        description = "Desktop idle backend selected by LG Buddy.";
      };

      idleTimeout = lib.mkOption {
        type = lib.types.ints.between 1 86400;
        default = 300;
        description = "Idle timeout in seconds.";
      };

      restorePolicy = lib.mkOption {
        type = lib.types.enum [
          "conservative"
          "aggressive"
        ];
        default = "conservative";
        description = "Policy controlling when LG Buddy restores the TV.";
      };
    };

    systemSleepWake = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether system lifecycle events control the TV.";
    };

    updates = {
      autoCheck = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Whether to run background release checks. Software updates remain
          controlled by the consuming flake input and lock file.
        '';
      };

      channel = lib.mkOption {
        type = lib.types.enum [
          "stable"
          "prerelease"
        ];
        default = "stable";
        description = "Release channel used by optional background checks.";
      };
    };

    pairingStateDirectory = lib.mkOption {
      type = lib.types.strMatching "/[^[:space:]]+";
      default = "/var/lib/lg-buddy/${cfg.user}";
      defaultText = lib.literalExpression ''"/var/lib/lg-buddy/''${config.services.lg-buddy.user}"'';
      description = "Writable directory containing persistent TV pairing state.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = builtins.hasAttr cfg.user config.users.users;
        message = "services.lg-buddy.user must name a configured user.";
      }
    ];

    warnings = lib.optional (!config.networking.networkmanager.enable) ''
      services.lg-buddy is enabled without NetworkManager; the logind lifecycle
      service remains available, but the NetworkManager pre-down gate is omitted.
    '';

    environment.systemPackages = [
      cfg.package
    ]
    ++ lib.optional (cfg.screen.backend != "gnome") pkgs.swayidle;

    systemd.tmpfiles.rules = [
      "d /run/lg_buddy 0755 root root -"
      "d /var/lib/lg-buddy 0755 root root -"
      "d ${cfg.pairingStateDirectory} 0700 ${cfg.user} ${userGroup} -"
    ];

    systemd.services.LG_Buddy = {
      description = "Control LG webOS TV at startup and shutdown";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      environment = commonEnvironment;
      unitConfig = {
        StartLimitIntervalSec = 30;
        StartLimitBurst = 5;
      };
      serviceConfig = rootServiceHardening // {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${cfg.package}/bin/lg-buddy startup boot";
        ExecStop = "${cfg.package}/bin/lg-buddy shutdown";
      };
    };

    systemd.services.LG_Buddy_lifecycle = {
      description = "LG Buddy system sleep and wake lifecycle monitor";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      environment = commonEnvironment;
      serviceConfig = rootServiceHardening // {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/lg-buddy lifecycle";
        Restart = "on-failure";
        RestartSec = 10;
      };
    };

    networking.networkmanager.dispatcherScripts = lib.mkIf config.networking.networkmanager.enable [
      {
        type = "pre-down";
        source = pkgs.writeShellScript "lg-buddy-networkmanager-pre-down" ''
          set -eu

          if [ "''${2:-}" != "pre-down" ]; then
              exit 0
          fi

          ${dispatcherEnvironment}
          exec ${cfg.package}/bin/lg-buddy nm-pre-down
        '';
      }
    ];

    systemd.user.services.LG_Buddy_screen = {
      description = "LG Buddy session monitor";
      wantedBy = [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      environment = commonEnvironment;
      path = lib.optional (cfg.screen.backend != "gnome") pkgs.swayidle;
      unitConfig.ConditionUser = cfg.user;
      serviceConfig = {
        ExecStart = "${cfg.package}/bin/lg-buddy monitor";
        Restart = "always";
        RestartSec = 10;
      };
    };

    systemd.user.services.LG_Buddy_update_check = {
      description = "LG Buddy background release check";
      after = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      environment = commonEnvironment;
      unitConfig.ConditionUser = cfg.user;
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${cfg.package}/bin/lg-buddy updates background-check";
      };
    };

    systemd.user.timers.LG_Buddy_update_check = {
      description = "LG Buddy background release check timer";
      wantedBy = lib.optional cfg.updates.autoCheck "graphical-session.target";
      after = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      unitConfig.ConditionUser = cfg.user;
      timerConfig = {
        OnCalendar = "weekly";
        RandomizedDelaySec = "12h";
        Persistent = true;
      };
    };
  };
}
